### PR TITLE
added upgrade script for existing users' accounts

### PR DESCRIPTION
**Pull request by julianlam**

### CODE REVIEW

**Comment by julianlam** [comment]
re: #5218

**Comment by julianlam** [comment]
You can ignore the second commit, it's just a merge to bring your branch in line with latest `master`

**Comment by pitaj** [comment]
Does this upgrade config.defaultLang too?

**Comment by pitaj** [comment]
Closed with 8fd7481

**Comment by julianlam** [comment]
Yep :100:

**Pull request closed without merging**
